# Generated by Django 4.1.7 on 2023-06-05 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expenses", "0003_scheduleexpense_periodic_task_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="payment_id",
            new_name="payment_method_id",
        ),
        migrations.AlterField(
            model_name="plan",
            name="plan_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="price_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="recurring_frequency",
            field=models.CharField(
                choices=[("month", "month"), ("year", "year"), ("once", "once")],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
