# Generated by Django 4.1.7 on 2023-06-07 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_subscription_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleexpense",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="expenses.plan",
            ),
        ),
    ]
