# Generated by Django 4.1.7 on 2023-06-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0006_alter_scheduleexpense_title_alter_subscription_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduleexpense",
            name="periodic_task",
        ),
    ]
