from django.urls import path
from .views import (ExpenseListCreateView, AddExpenseLoadView, ExpenseRetrieveUpdateDestroyAPIView,
                    ExpenseUpdateLoadView,
                    MonthBudgetListView, AddMonthExpenseLoadview, MonthExpenseUpdateLoadView, MonthBudgetLoadView,
                    MonthBudgetDetailView,
                    MonthlyExpenseReportView, YearlyExpenseReportView, CustomExpenseReportView, ScheduleExpenseLoadView,
                    ExpenseReportLoadView,
                    AddScheduleExpenseLoadview, MonthlyExpenseReportView1, YearlyExpenseReportView1,
                    CustomExpenseReportView1, ExpenseReportLoadView1,
                    ScheduleExpenseListCreateView, ScheduleExpenseRetrieveUpdateDestroyAPIView,
                    UpdateScheduleExpenseLoadview, PlansLoadView, PlanCreateListAPIView,
                    SubscriptionAPIView, PaymentLoadView, WebhookView
                    )

urlpatterns = [
    path("", AddExpenseLoadView, name="addExpense"),
    path("api/", ExpenseListCreateView.as_view()),
    path("<int:id>/", ExpenseUpdateLoadView, name="update_expense"),
    path("api/<int:id>/", ExpenseRetrieveUpdateDestroyAPIView.as_view()),
    path("add-month/", AddMonthExpenseLoadview, name="addmonthbudget"),
    path("api/month/", MonthBudgetListView.as_view()),
    path("month/", MonthBudgetLoadView, name="monthbudget"),
    path("api/month/", MonthBudgetListView.as_view()),
    path("api/month/<int:id>/", MonthBudgetDetailView.as_view()),
    path("month/<int:id>/", MonthExpenseUpdateLoadView),
    path("api/month/v1/report/", MonthlyExpenseReportView.as_view()),
    path("api/year/v1/report/", YearlyExpenseReportView.as_view()),
    path("api/custom/v1/report/", CustomExpenseReportView.as_view()),
    path("schedule/", ScheduleExpenseLoadView, name="schedule_expense"),
    path("report/", ExpenseReportLoadView, name="report_expense"),
    path("add/schedule/", AddScheduleExpenseLoadview, name="add_schedule_expense"),
    path("api/v2/month/report/", MonthlyExpenseReportView1.as_view()),
    path("api/v2/year/report/", YearlyExpenseReportView1.as_view()),
    path("api/v2/custom/report/", CustomExpenseReportView1.as_view()),
    path("v2/report/", ExpenseReportLoadView1, name="report_expense1"),
    path("api/schedule/", ScheduleExpenseListCreateView.as_view()),
    path("api/schedule/<int:id>/", ScheduleExpenseRetrieveUpdateDestroyAPIView.as_view()),
    path("schedule/<int:id>/", UpdateScheduleExpenseLoadview),
    path("plan/", PlansLoadView, name="SubscriptionPlan"),
    path("api/plans/", PlanCreateListAPIView.as_view()),
    path("payments/<str:id>/", PaymentLoadView, name="Payment"),
    path("api/subscriptions/", SubscriptionAPIView.as_view()),
    path("api/stripe-webhook/", WebhookView.as_view()),

]
